# Generated by Django 3.1.4 on 2021-01-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('login', models.CharField(max_length=30, verbose_name='Login')),
                ('email', models.EmailField(max_length=80, verbose_name='Email Address')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('address_1', models.CharField(blank=True, max_length=60, null=True, verbose_name='Corporate Address')),
                ('address_2', models.CharField(max_length=60, verbose_name='Street Address')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('state_or_province', models.CharField(max_length=30, verbose_name='State / Province')),
                ('county', models.CharField(blank=True, max_length=30, verbose_name='County')),
                ('postal_code', models.CharField(max_length=14, verbose_name='Postal / Zip Code')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
            },
        ),
    ]
