# Generated by Django 3.1.4 on 2021-01-04 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_productcategory'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Order Date and Time')),
                ('payment_method', models.CharField(max_length=20, verbose_name='Payment method')),
                ('delivery_method', models.CharField(max_length=20, verbose_name='Payment method')),
                ('delivery_date', models.DateTimeField(verbose_name='Delivery Date')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Good')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date and Time Created')),
                ('item_price', models.FloatField(verbose_name='Item Price')),
                ('quantity', models.IntegerField(verbose_name='Products Quantity')),
                ('sub_total', models.FloatField(verbose_name='Sub total')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Good')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
            },
        ),
    ]
